/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mips;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import mips.InstructionTypes.Instruction;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left = new javax.swing.JPanel();
        CreatedLabel = new javax.swing.JLabel();
        AuthorsLabel = new javax.swing.JLabel();
        CodeLinkLabel = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        MainTitleLabel = new javax.swing.JLabel();
        SubtitleLabel = new javax.swing.JLabel();
        MipsButton = new javax.swing.JButton();
        CheckpointButton = new javax.swing.JButton();
        NoFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Left.setBackground(new java.awt.Color(39, 39, 39));
        Left.setMaximumSize(new java.awt.Dimension(400, 500));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        CreatedLabel.setBackground(new java.awt.Color(241, 241, 241));
        CreatedLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreatedLabel.setForeground(new java.awt.Color(241, 241, 241));
        CreatedLabel.setText("Created By:");

        AuthorsLabel.setBackground(new java.awt.Color(241, 241, 241));
        AuthorsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AuthorsLabel.setForeground(new java.awt.Color(241, 241, 241));
        AuthorsLabel.setText("<html>Selma Eklund<br>Natalie Spiro<br>Jacob McGowan<br>Jacob Vorndran<html>");

        CodeLinkLabel.setBackground(new java.awt.Color(241, 241, 241));
        CodeLinkLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CodeLinkLabel.setForeground(new java.awt.Color(241, 241, 241));
        CodeLinkLabel.setText("See The Code");

        LogoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        LogoLabel.setAlignmentX(0.5F);
        LogoLabel.setPreferredSize(new java.awt.Dimension(300, 300));
        LogoLabel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreatedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AuthorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CodeLinkLabel)
                .addGap(20, 20, 20))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CreatedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AuthorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeLinkLabel))
                .addGap(20, 20, 20))
        );

        getContentPane().add(Left);

        Right.setBackground(new java.awt.Color(241, 241, 241));
        Right.setMaximumSize(new java.awt.Dimension(400, 500));
        Right.setMinimumSize(new java.awt.Dimension(400, 500));

        MainTitleLabel.setBackground(new java.awt.Color(39, 39, 39));
        MainTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        MainTitleLabel.setForeground(new java.awt.Color(39, 39, 39));
        MainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitleLabel.setText("SIC VM with MIPS");

        SubtitleLabel.setBackground(new java.awt.Color(39, 39, 39));
        SubtitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubtitleLabel.setForeground(new java.awt.Color(39, 39, 39));
        SubtitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubtitleLabel.setText("Run MIPS Assembly Files");

        MipsButton.setBackground(new java.awt.Color(39, 39, 39));
        MipsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MipsButton.setForeground(new java.awt.Color(241, 241, 241));
        MipsButton.setText("Load MIPS File");
        MipsButton.setPreferredSize(new java.awt.Dimension(175, 25));
        MipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MipsButtonActionPerformed(evt);
            }
        });

        CheckpointButton.setBackground(new java.awt.Color(39, 39, 39));
        CheckpointButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckpointButton.setForeground(new java.awt.Color(241, 241, 241));
        CheckpointButton.setText("Load Checkpoint File");
        CheckpointButton.setPreferredSize(new java.awt.Dimension(175, 25));
        CheckpointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckpointButtonActionPerformed(evt);
            }
        });

        NoFileButton.setBackground(new java.awt.Color(39, 39, 39));
        NoFileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoFileButton.setForeground(new java.awt.Color(241, 241, 241));
        NoFileButton.setText("Load Without File");
        NoFileButton.setPreferredSize(new java.awt.Dimension(175, 25));
        NoFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckpointButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(MainTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(MipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(CheckpointButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NoFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Right);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MipsButtonActionPerformed
        // Set up fileChooser and open it //
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileFilter() {

            @Override
            public String getDescription() {
                return "*.asm";
            }

            @Override
            public boolean accept(File f) {
                return f.getName().endsWith(".asm");
            }
        });
        
        fileChooser.showOpenDialog(this);
        File file = fileChooser.getSelectedFile();
        
        String fileAsString = "";
        
        LinkedList<Instruction> stream = new LinkedList<>();;
        
        // Open File And Read Out To A String //
        try {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            
            String line = reader.readLine();
            
            Decoder decoder = new Decoder();
            stream = decoder.decode(file);

            while(line!=null)
            {
                System.out.print(line);
                
                // Add To String and Remove Comments //
                fileAsString += line.split("#")[0] + "\n";
                line = reader.readLine();
            }
            
            reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
            fileAsString = "bad";
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MIPS.OpenMIPSEditor(fileAsString, stream);
    }//GEN-LAST:event_MipsButtonActionPerformed

    private void CheckpointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckpointButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CheckpointButtonActionPerformed

    private void NoFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoFileButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NoFileButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorsLabel;
    private javax.swing.JButton CheckpointButton;
    private javax.swing.JLabel CodeLinkLabel;
    private javax.swing.JLabel CreatedLabel;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JLabel MainTitleLabel;
    private javax.swing.JButton MipsButton;
    private javax.swing.JButton NoFileButton;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel SubtitleLabel;
    // End of variables declaration//GEN-END:variables
}
