/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sicvm;

import javax.swing.table.TableColumn;

/**
 *
 * @author jacob
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BaseChanger = new javax.swing.ButtonGroup();
        ControlPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Editor = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProgramInformation = new javax.swing.JPanel();
        Memory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RegisterTable = new javax.swing.JTable();
        Binary = new javax.swing.JRadioButton();
        Hexadecimal = new javax.swing.JRadioButton();
        Decimal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MIPS Emulator");
        setMaximumSize(new java.awt.Dimension(1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        ControlPanel.setBackground(new java.awt.Color(46, 40, 42));
        ControlPanel.setPreferredSize(new java.awt.Dimension(110, 700));

        jButton1.setBackground(new java.awt.Color(66, 61, 63));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OneStep.png"))); // NOI18N
        jButton1.setToolTipText("Single Step");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 75));

        jButton2.setBackground(new java.awt.Color(66, 61, 63));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MicroStep.png"))); // NOI18N
        jButton2.setToolTipText("Micro Step");
        jButton2.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton2.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton2.setPreferredSize(new java.awt.Dimension(75, 75));

        jButton3.setBackground(new java.awt.Color(66, 61, 63));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FullSpeed.png"))); // NOI18N
        jButton3.setToolTipText("Run Full Speed");
        jButton3.setMaximumSize(new java.awt.Dimension(75, 75));
        jButton3.setMinimumSize(new java.awt.Dimension(75, 75));
        jButton3.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        getContentPane().add(ControlPanel);

        Editor.setBackground(new java.awt.Color(66, 61, 63));
        Editor.setForeground(new java.awt.Color(66, 61, 63));
        Editor.setMaximumSize(new java.awt.Dimension(915, 700));
        Editor.setMinimumSize(new java.awt.Dimension(915, 700));

        jTabbedPane1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(880, 400));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(880, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(880, 400));

        ProgramInformation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProgramInformation.setMaximumSize(new java.awt.Dimension(880, 400));
        ProgramInformation.setMinimumSize(new java.awt.Dimension(880, 400));
        ProgramInformation.setPreferredSize(new java.awt.Dimension(880, 400));

        javax.swing.GroupLayout ProgramInformationLayout = new javax.swing.GroupLayout(ProgramInformation);
        ProgramInformation.setLayout(ProgramInformationLayout);
        ProgramInformationLayout.setHorizontalGroup(
            ProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        ProgramInformationLayout.setVerticalGroup(
            ProgramInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Program Information", ProgramInformation);

        Memory.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        Memory.setMaximumSize(new java.awt.Dimension(880, 400));
        Memory.setMinimumSize(new java.awt.Dimension(880, 400));
        Memory.setPreferredSize(new java.awt.Dimension(880, 400));

        jScrollPane1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N

        RegisterTable.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        RegisterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RegisterTable);

        javax.swing.GroupLayout MemoryLayout = new javax.swing.GroupLayout(Memory);
        Memory.setLayout(MemoryLayout);
        MemoryLayout.setHorizontalGroup(
            MemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemoryLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        MemoryLayout.setVerticalGroup(
            MemoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemoryLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Memory", Memory);

        Binary.setBackground(new java.awt.Color(66, 61, 63));
        BaseChanger.add(Binary);
        Binary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Binary.setForeground(new java.awt.Color(253, 255, 252));
        Binary.setSelected(true);
        Binary.setText("Binary");

        Hexadecimal.setBackground(new java.awt.Color(66, 61, 63));
        BaseChanger.add(Hexadecimal);
        Hexadecimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Hexadecimal.setForeground(new java.awt.Color(253, 255, 252));
        Hexadecimal.setText("Hexadecimal");

        Decimal.setBackground(new java.awt.Color(66, 61, 63));
        BaseChanger.add(Decimal);
        Decimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Decimal.setForeground(new java.awt.Color(253, 255, 252));
        Decimal.setText("Decimal");

        javax.swing.GroupLayout EditorLayout = new javax.swing.GroupLayout(Editor);
        Editor.setLayout(EditorLayout);
        EditorLayout.setHorizontalGroup(
            EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditorLayout.createSequentialGroup()
                        .addComponent(Binary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hexadecimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Decimal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EditorLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        EditorLayout.setVerticalGroup(
            EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(EditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Binary)
                    .addComponent(Hexadecimal)
                    .addComponent(Decimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Editor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }
    
    public void UpdateRegisterTable()
    {
        TableColumn newCol = new TableColumn();
        RegisterTable.addColumn(newCol);
        
        RegisterTable
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BaseChanger;
    private javax.swing.JRadioButton Binary;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JRadioButton Decimal;
    private javax.swing.JPanel Editor;
    private javax.swing.JRadioButton Hexadecimal;
    private javax.swing.JPanel Memory;
    private javax.swing.JPanel ProgramInformation;
    private javax.swing.JTable RegisterTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
