/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sicvm;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jacob
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vanityPanel = new javax.swing.JPanel();
        nameTag1 = new java.awt.Label();
        nameTag2 = new java.awt.Label();
        nameTag3 = new java.awt.Label();
        nameTag4 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        credit1 = new java.awt.Label();
        credit2 = new java.awt.Label();
        credit3 = new java.awt.Label();
        credit4 = new java.awt.Label();
        nameTag5 = new java.awt.Label();
        menuPanel = new javax.swing.JPanel();
        menuTitle = new javax.swing.JLabel();
        openTextButton = new javax.swing.JButton();
        openManuel = new javax.swing.JButton();
        openGitHub = new javax.swing.JButton();
        menuDescriptor1 = new javax.swing.JLabel();
        menuDescriptor2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SICVM - MIPS Sim");
        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setName("SICVM - MIPS Sim"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        vanityPanel.setBackground(new java.awt.Color(46, 40, 42));
        vanityPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        vanityPanel.setMinimumSize(new java.awt.Dimension(400, 500));

        nameTag1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        nameTag1.setForeground(new java.awt.Color(253, 255, 252));
        nameTag1.setText("Selma Eklund");

        nameTag2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        nameTag2.setForeground(new java.awt.Color(253, 255, 252));
        nameTag2.setText("Natalie Spiro");

        nameTag3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        nameTag3.setForeground(new java.awt.Color(253, 255, 252));
        nameTag3.setText("Jacob McGowan");

        nameTag4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        nameTag4.setForeground(new java.awt.Color(253, 255, 252));
        nameTag4.setText("Jacob Vorndran");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N

        credit1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        credit1.setForeground(new java.awt.Color(253, 255, 252));
        credit1.setText("- Checkpoints");

        credit2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        credit2.setForeground(new java.awt.Color(253, 255, 252));
        credit2.setText("- MIPS Conversion");

        credit3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        credit3.setForeground(new java.awt.Color(253, 255, 252));
        credit3.setText("- Control & GUI");

        credit4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        credit4.setForeground(new java.awt.Color(253, 255, 252));
        credit4.setText("- Memory Layout");

        nameTag5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        nameTag5.setForeground(new java.awt.Color(253, 255, 252));
        nameTag5.setText("PROJECT MEMBERS");

        javax.swing.GroupLayout vanityPanelLayout = new javax.swing.GroupLayout(vanityPanel);
        vanityPanel.setLayout(vanityPanelLayout);
        vanityPanelLayout.setHorizontalGroup(
            vanityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vanityPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vanityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nameTag2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTag3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(nameTag4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTag1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vanityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(credit4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credit3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credit2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credit1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(vanityPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(vanityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vanityPanelLayout.createSequentialGroup()
                        .addComponent(nameTag5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        vanityPanelLayout.setVerticalGroup(
            vanityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vanityPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(nameTag5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vanityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vanityPanelLayout.createSequentialGroup()
                        .addComponent(nameTag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(nameTag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(nameTag3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(nameTag4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vanityPanelLayout.createSequentialGroup()
                        .addComponent(credit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(credit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(credit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(credit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(vanityPanel);

        menuPanel.setBackground(new java.awt.Color(253, 255, 252));
        menuPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        menuPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        menuPanel.setPreferredSize(new java.awt.Dimension(400, 500));

        menuTitle.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        menuTitle.setText("SICVM - MIPS Emulator");

        openTextButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        openTextButton.setText("Open File");
        openTextButton.setToolTipText("");
        openTextButton.setMaximumSize(new java.awt.Dimension(200, 28));
        openTextButton.setMinimumSize(new java.awt.Dimension(200, 28));
        openTextButton.setPreferredSize(new java.awt.Dimension(200, 28));
        openTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openTextButtonMouseClicked(evt);
            }
        });

        openManuel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        openManuel.setText("SICVM Manuel");
        openManuel.setToolTipText("");
        openManuel.setMaximumSize(new java.awt.Dimension(200, 28));
        openManuel.setMinimumSize(new java.awt.Dimension(200, 28));
        openManuel.setPreferredSize(new java.awt.Dimension(200, 28));
        openManuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openManuelMouseClicked(evt);
            }
        });

        openGitHub.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        openGitHub.setText("Open GitHub");
        openGitHub.setToolTipText("");
        openGitHub.setMaximumSize(new java.awt.Dimension(200, 28));
        openGitHub.setMinimumSize(new java.awt.Dimension(200, 28));
        openGitHub.setPreferredSize(new java.awt.Dimension(200, 28));
        openGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openGitHubMouseClicked(evt);
            }
        });

        menuDescriptor1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        menuDescriptor1.setText("Run MIPS Assembly and Save Checkpoints");

        menuDescriptor2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        menuDescriptor2.setText("Modify Memory and Control Each Step");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(openGitHub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openManuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(menuDescriptor1)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(menuDescriptor2)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(menuTitle)
                        .addGap(23, 23, 23))))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(menuTitle)
                .addGap(40, 40, 40)
                .addComponent(menuDescriptor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDescriptor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(openTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openManuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openGitHub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        getContentPane().add(menuPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openManuelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openManuelMouseClicked
        // Open Manuel Page //
        SICVM.OpenManuelPage();
    }//GEN-LAST:event_openManuelMouseClicked

    private void openTextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTextButtonMouseClicked
        try {
            // Attempt To Open A File That The User Wants To Use //
            if(OpenMIPSFile.Open() == 1)
            {
                SICVM.OpenFile();
            }
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openTextButtonMouseClicked

    private void openGitHubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openGitHubMouseClicked
        // Open GitHub Page //
        SICVM.OpenGitHubPage();
    }//GEN-LAST:event_openGitHubMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label credit1;
    private java.awt.Label credit2;
    private java.awt.Label credit3;
    private java.awt.Label credit4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menuDescriptor1;
    private javax.swing.JLabel menuDescriptor2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel menuTitle;
    private java.awt.Label nameTag1;
    private java.awt.Label nameTag2;
    private java.awt.Label nameTag3;
    private java.awt.Label nameTag4;
    private java.awt.Label nameTag5;
    private javax.swing.JButton openGitHub;
    private javax.swing.JButton openManuel;
    private javax.swing.JButton openTextButton;
    private javax.swing.JPanel vanityPanel;
    // End of variables declaration//GEN-END:variables
}
